### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by benze** [xin053/hsperfdata#2]
I'm trying to build ur latest using the instructions in the README, but they don't seem to inline with the latest version of go.

I downgraded to go 1.8, but it still doesn't compile due to different file structures/etc.

What is the correct way to build your utility with go 1.16+ ?

Thanks,

Eric

**Comment by xin053** [comment]
I have update this project to use go module(`go 1.12+`), and update the `README`.

The beat way to use this project is to use as a library in your golang project.

Or you can use the `hstat` command (download from release page or build yourself) to do some test.
